stages:
  - build
  - test
  - deploy
  - deployment tests
  - cache

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ./session2/static-website/node_modules/
  policy: pull

update cache:
  stage: cache
  image: node:14-alpine
  script:
    - cd ./session2/static-website/
    - npm install
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - ./session2/static-website/node_modules/
    policy: push
  only:
    - schedules
    
build wesite:
  stage: build
  image: node:14-alpine
  script:
    - echo $CI_COMMIT_SHORT_SHA
    - ls -al
    - cd ./session2/static-website/
    - npm install
    - npm install -g gatsby-cli
    - gatsby build
    - sed -i "s/%%VERSION%%/$CI_COMMIT_SHORT_SHA/" ./public/index.html
  artifacts:
    paths:
      - ./session2/static-website/public
  except:
    - schedules

test artifacts:
  stage: test
  image: alpine:latest
  cache: {}
  script:
    - ls -al
    - grep "Gatsby" ./session2/static-website/public/index.html
  except:
    - schedules

test website:
  stage: test
  image: node:14-alpine
  script:
    - ls -al
    - cd ./session2/static-website/
    - npm install
    - npm install -g gatsby-cli
    - apk update
    - apk add curl
    - gatsby serve & 
    - sleep 3
    - curl "http://localhost:9000" | tac | tac | grep -q "Gatsby"
  except:
    - schedules    

deploy to surge:
  stage: deploy
  image: node:14-alpine
  cache: {}
  script:
    - ls -al
    - cd ./session2/static-website/
    - npm install --g surge
    - surge --project ./public --domain a1824jj.aiit.surge.sh
  except:
    - schedules

test deployment:
  stage: deployment tests
  image: alpine:latest
  cache: {}
  script:
    - apk add --no-cache curl
    - curl -s "http://a1824jj.aiit.surge.sh" | grep -q "Hi people"
    - curl -s "http://a1824jj.aiit.surge.sh" | grep -q "$CI_COMMIT_SHORT_SHA"
  except:
    - schedules