stages:
  - build
  - test
  - deploy staging
  - deploy production
  - production tests
  - cache

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ./session2/static-website/node_modules/
  policy: pull

variables:
  STAGING_DOMAIN: a1824jj-staging.aiit.surge.sh
  PRODUCTION_DOMAIN: a1824jj.aiit.surge.sh

update cache:
  stage: cache
  image: node:14-alpine
  script:
    - cd ./session2/static-website/
    - npm install
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - ./session2/static-website/node_modules/
    policy: push
  only:
    - schedules
    
build wesite:
  stage: build
  image: node:14-alpine
  script:
    - echo $CI_COMMIT_SHORT_SHA
    - ls -al
    - cd ./session2/static-website/
    - npm install
    - npm install -g gatsby-cli
    - gatsby build
    - sed -i "s/%%VERSION%%/$CI_COMMIT_SHORT_SHA/" ./public/index.html
  artifacts:
    paths:
      - ./session2/static-website/public
  except:
    - schedules

test artifacts:
  stage: test
  image: alpine:latest
  cache: {}
  script:
    - ls -al
    - grep "Gatsby" ./session2/static-website/public/index.html
  except:
    - schedules

test website:
  stage: test
  image: node:14-alpine
  script:
    - ls -al
    - cd ./session2/static-website/
    - npm install
    - npm install -g gatsby-cli
    - apk update
    - apk add curl
    - gatsby serve & 
    - sleep 3
    - curl "http://localhost:9000" | tac | tac | grep -q "Gatsby"
  except:
    - schedules    

deploy staging:
  stage: deploy staging
  environment:
    name: staging
    url: http://$STAGING_DOMAIN
  image: node:14-alpine
  cache: {}
  script:
    - ls -al
    - cd ./session2/static-website/
    - npm install --g surge
    - surge --project ./public --domain $STAGING_DOMAIN
  except:
    - schedules
  only:
    - master

deploy production:
  stage: deploy production
  environment:
    name: production
    url: http://$PRODUCTION_DOMAIN
  image: node:14-alpine
  cache: {}
  script:
    - ls -al
    - cd ./session2/static-website/
    - npm install --g surge
    - surge --project ./public --domain $PRODUCTION_DOMAIN
  except:
    - schedules
  when: manual
  allow_failure: false
  only:
    - master

test deployment:
  stage: production tests
  image: alpine:latest
  cache: {}
  script:
    - apk add --no-cache curl
    - curl -s "http://$PRODUCTION_DOMAIN" | grep -q "Hi people"
    - curl -s "http://$PRODUCTION_DOMAIN" | grep -q "$CI_COMMIT_SHORT_SHA"
  except:
    - schedules
  only:
    - master