stages:
  - build
  - test

build wesite:
  stage: build
  image: node:14-alpine
  script:
    - ls -al
    - cd ./session2/static-website/
    - npm install
    - npm install -g gatsby-cli
    - gatsby build
  artifacts:
    paths:
      - ./session2/static-website/public

test artifacts:
  stage: test
  image: alpine:latest
  script:
    - ls -al
    - grep "Gatsby" ./session2/static-website/public/index.html
    - grep "xxxxxx" ./session2/static-website/public/index.html