build wesite:
  image: node:14-alpine
  script:
    - ls -al
    - cd ./session2/static-website/
    - npm install
    - npm install -g gatsby-cli
    - gatsby build
  artifacts:
    paths:
      - ./public